### ISSUE TITLE
Use own spectrals

### ISSUE THREAD

**Issue by de-gozaru** [mkazhdan/ECHODescriptors#2]
Hi @mkazhdan @twmitchel 

Thank you for open-sourcing the code.

I'm trying to test the ECHO code, but with a spectral decomposition  I computed in advance using another code. I added the following function:
```cpp
// function that sets the values _eigenvalues and _eigenvectors from function input
template< typename Real >
template< typename GReal >
void Spectrum< Real >::setEigenValuesAndVectors( const std::vector< Real > &eigenvalues , const std::vector< std::vector< Real > > &eigenvectors, 
const std::vector< Point3D< GReal > > &vertices , const std::vector< TriangleIndex > &triangles , bool lump)
{
	_eigenvalues = eigenvalues;
	_eigenvectors = eigenvectors;

	std::vector< TriangleIndex > _triangles = triangles;
	FEM::RiemannianMesh< Real > mesh( GetPointer( _triangles ) , _triangles.size() );
	mesh.template setMetricFromEmbedding< 3 >( [&]( unsigned int idx ){ return Point3D< Real >( vertices[idx] ); } );
	mesh.makeUnitArea();
	SparseMatrix< Real , int > M = mesh.template massMatrix< FEM::BASIS_0_WHITNEY >( lump );

	// Normalize the eigenvectors
	for( int i=0 ; i<_eigenvectors.size() ; i++ )
	{
		Real l2Norm = 0;

		#pragma omp parallel for reduction( + : l2Norm )
		for( int j=0 ; j<M.rows ; j++ ) for( int k=0 ; k<M.rowSizes[j] ; k++ ) l2Norm += M[j][k].Value * _eigenvectors[i][j] * _eigenvectors[i][ M[j][k].N ];
		l2Norm = (Real)sqrt( l2Norm );

		#pragma omp parallel for
		for( int j=0 ; j<_eigenvectors[i].size() ; j++ ) _eigenvectors[i][j] /= l2Norm;
	}
}

```

However, when I use this, the computation became very slow. I tried to debug it and found that this is because of the parameter `tau`, the default value is too big for my computed eigenvectors, and if I use a smaller `tau` value, the computation becomes reasonable.

My question is what is this happening, since I'm normalizing the eigenvectors the same way you did in your code, and also checked that my eigenvalues are equal to yours?

Thank you in advance!

PS: It should be noted that the meshes that I used for testing are of unit norm by default, so `mesh.makeUnitArea()` won't change anything a priori, also the spectral decomposition was computed using unit norm shapes.

**Comment by twmitchel** [comment]
Hi @de-gozaru 

In lines 271-278 of `GetDescriptor.cpp` after computing the HKS we re-normalize the eigenvectors based on the chosen distance. Are you doing this as well?

**Comment by de-gozaru** [comment]
Hi @twmitchel

Thank you for your answer!

Yes, I didn't change the structure of `GetDescriptor` code, just refactored it, and it's working If the spectral are computed using the `spectrum.set` function, but if I want to load my own computed spectrals (it should be noted that the my eigen values are equal to those produced by the code, up to a small perturbation), it becomes very slow, and I was wondering if there is a function in the code that changes the area of the mesh, or normalize the eigenvectors, that I'm not aware of!

Also, I'm creating a feature for each point in my shape, so I have a matrix of size `N x 441` (I used hradiaus=10), do you see any inconvenient in normalizing the features row-wise, using L2 norm? I'm suggesting this because the values of the features are very small (in the order of 1e-4) and this may cause numerical issues? also, is it normal that the values of the feature are very small?

I hope this answers your question!

**Comment by twmitchel** [comment]
@de-gozaru 

To confirm, you're saying that if you load your own eigenspectrum and compute the descriptor it is much slower than using our eigenspectrum with exactly the same parameters?

Do you also get very small magnitude features using our eigenspectrum?

**Comment by de-gozaru** [comment]
Hi @twmitchel 

Yes, exactly!

When I use my own spectral decomposition, even though the eigenvalues are approximaltely equal, it takes too much time to compute one ECHO feature, after debugging, I found this is because the `computeSpectralDistancesAbout` function!

For your second question, yes! using the code you provided, for a mesh that has a surface area of 1, tau=0.1, hradius=10, the ECHO features are very small, this is why I though it maybe a good  idea to normalize them to have a unit L2 norm!

Hope this answers your question!

**Comment by twmitchel** [comment]
@de-gozaru 

Using a smaller value of `tau` with your custom spectrum should be fine. I'd recommend marking the vertices within the descriptor radius and visualizing them to make sure that the patch size is appropriate for what you're going for.

Normalizing the descriptor values is fine (we in fact comment on this in the paper). I'd also recommend using a smaller `hRadius` to start, say `hRadius=5`.

**Comment by de-gozaru** [comment]
Hi @twmitchel 
Thank you for your answer!

This answers my question, I'll close the issue for now, and come back if I have another question!
Best,
